title: Config Schema
type: object
properties:
  title:
    type: string
  foo:
    type: boolean
  pages:
    type: array
    items:
      type: object
      properties:
        path:
          type: string
          pattern: "^[a-zA-Z0-9_\\-/]+$"
        title:
          type: string
        content:
          type: string
      required: ["title", "content", "path"]
      additionalProperties: false
additionalProperties: false
required: ["foo", "title"]